package com.hypernova.media.visualizer;

public enum VisualizerMode {
    IDLE,
    RADIO_BUFFERING,
    RADIO_PLAYING,
    LIBRARY_AUDIO_PLAYING,
    LIBRARY_VIDEO_PLAYING,
    USB_NO_DEVICE,
    USB_INSERTED,
    USB_SCANNING,
    USB_REMOVED,
    BLUETOOTH_CONNECTING,
    BLUETOOTH_CONNECTED,
    BLUETOOTH_PLAYING,
    PAUSED,
    ERROR
}
